### ISSUE TITLE
NoMethodError: undefined method `text' for nil:NilClass

### ISSUE THREAD

**Issue by ramdanplusplus** [mlpinit/bootleg#1]
Hi,

I got error "NoMethodError: undefined method `text' for nil:NilClass" when I tried to run Bootleg.load('12201') in console.

Thanks

**Comment by mlpinit** [comment]
Hey, really sorry for the 2 year late response... :( I obviously didn't pay much attention to this gem. I updated the gem since so this issues is no longer relevant.
